language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - release
  
notifications:
  email: false
 
before_install:
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("FactoredEikonalFastMarching"); Pkg.test("FactoredEikonalFastMarching"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("FactoredEikonalFastMarching")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'